version: "3.8"

services:
  app:
    container_name: amazon-clone-dev
    image: amazon-clone-dev
    build:
      context: .
      target: development
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
